application: cdisc-share-template-checker
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img

- url: /.*
  script: share.app
  login: required
- url: /checker/.*
  script: share.app
  login: required	

libraries:
- name: jinja2
  version: latest